### ISSUE TITLE
Library not working in IE11

### ISSUE THREAD

**Issue by samuelsramko** [gerlocian/ng-html5dragdrop#1]
Hi.
I run into bug in IE11, when start dragging element an error occurred. 
SCRIPT65535: Unexpected call to method or property access.

It occurs here.
`element.on('dragStart', function (Event) { event.dataTransfer.setData('text/plain', element.attr('id'));`

In IE according to standard, setData() and getData() can only be called with 'Text' or 'text' properties. https://msdn.microsoft.com/en-us/library/ms536744(v=vs.85).aspx

Solution is to change these fields.

Thanks in advance.

**Comment by samuelsramko** [comment]
I created pull request for this issue. https://github.com/gerlocian/ng-html5dragdrop/pull/2

**Comment by gerlocian** [comment]
Sorry it took so long to get back to you on this. After reading the documentation that you provided, you are right, I simply missed it. The other browsers seem to be more lenient on the values for format, but IE seems to be more strict. I'll merge in your change and set up a new release. Thanks for catching this!
