### ISSUE TITLE
Support for multiple datatypes would be nice.

### ISSUE THREAD

**Issue by michaelkrog** [gerlocian/ng-html5dragdrop#7]
When a drag starts the dataTransfer has a locked type:

```
dataTransfer.setData('text', ...
```

https://github.com/gerlocian/ng-html5dragdrop/blob/develop/src/assets/js/directives/drag.js#L59

It would be nice to be able to define the datatype. Some dropzones may support multiple datatypes and do different things accordingly.

**Comment by gerlocian** [comment]
Hi Michael,

I haven't ignored this, I've been out of town. I'm noodling on this now trying to figure out the best way to set that up. Give me some time to figure that out and I'll come back to it.

**Comment by gerlocian** [comment]
Michael,

Sorry, this took so long. I've just created a new release that should handle this request. Please take a look at the documentation and let me know if this will suit your needs.

Thanks!
